---
title: "Final projects!"
author: "NRES 470/670"
date: "Spring 2023"
output: 
  html_document: 
    theme: spacelab
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
```

## Final projects for NRES 470

Students will work in groups of ~3-4 people to perform a population viability analysis (PVA) to rank conservation or management actions for a species of conservation concern (species of your choice!). Grading will be based on finished products (written and oral presentations) as well as project proposals and written peer reviews.

## Overview

- Select a species and management question of interest. 
- Perform a thorough literature review on your species of interest- collect all the information you can about life history (e.g., age at maturity), key vital rates (e.g., stage-structured birth and survival rates), carrying capacity, etc. 
- Construct a population viability analysis (PVA) model, parameterized using the best information you can find in the literature (using InsightMaker, R, or Vortex as a modeling platform). 
- Use your PVA model to run **scenario tests** that address a conservation or management question (to test your research question)
- Use the model results to rank conservation or management actions for your species or population of interest
- _Write up the results_ and present your results to the class!

## Timeline (updated)

- **PROPOSAL:** Due Fri March 10!
- **INITIAL PVA** Due Wed April 12: description of how your PVA model works and where the parameter estimates come from -- and a link to a working PVA model!     
- **DRAFT FINAL PAPER:** Due Mon April 24.
- **PEER REVIEWS:** Fri Apr 28 in lab.
- **FINAL PRESENTATIONS:** Wed May 3 and Fri May 5!
- **FINAL FINAL PAPER:** Due Wed May 17

Remember that the semester will get crazy at the end (including for your instructors). Plan ahead! 

## First project-related assignment: the proposal!

Your project proposal (approx 1 pg) will consist of:  

1. **Title**: should indicate what species you are modeling, and hint at what question(s) will be addressed   
2. **Project participants**: provide names of all project participants (3-4).   
3. **Research question(s)**: Provide one or more testable and management-relevant questions that you plan to address using your population model. Putting "too many" questions is okay for now- we will talk them over in our project meetings right before spring break.  
4. **Project rationale**: Describe your rationale for choosing this species, and explain why your management/conservation question(s) are important to address. Be as specific as possible! Convince your instructor/TA that your project is **interesting**!    
5. **Data sources**: Describe one or more information sources you plan to use to guide PVA construction and parameterization (convince your instructor/TA that your project is **doable**!)  

Some key parameters you will likely need for your PVA model (and will be searching the literature for!) are: 

- *survival rates* (usually age- or stage-structured)     
- *birth rates* (usually age- or stage structured) and *age at maturity*    
- *initial abundance*    
- *carrying capacity (K)* (potentially for several subpopulations in a metapopulation model)     
- *density dependence* (how do vital rates change as density increases?)         
- *stochasticity* (annual variability in survival and birth rates)     
- *dispersal rates* (for metapopulation models)      
- *habitat quality* (for metapopulation models)       
- *response to management** (linkages between management activities and vital rates - for running scenario tests!)       

We have gone over many of these concepts in class already- PVA is just a way of putting all the concepts from this class together in a single model! You can get the above information directly from the published literature (or unpublished reports), or you estimate these parameters yourself using raw data (which we haven't yet gone over in class- and which you are not expected to do!!). If all else fails, you can use published records for similar species as a proxy (assuming that the vital rates are approximately the same)!

## Second project-related assignment: the initial PVA!

Your **initial parameterized PVA model** will consist of:  

1. **A ready-to-run PVA model**, in whatever software framework you are using (InsightMaker or R). This model does not need to be your "final" model, but it should work (e.g., produce results), the parameter estimates should be backed by some evidence or rationale (see below), and it should be capable of running your proposed scenario tests.

2. **Written rationale/evidence for all of your parameter estimates** and key modeling decisions.   
    a. For each major decision you made in constructing the model, describe the information you used to back up your decision (and the sources of this information). Decisions include: how many stage or age classes in your model, what are your survival and fecundity rates (transition rates), what is your initial abundance(s), how does population density affect vital rates in your model (density-dependence -- including Allee effects if applicable), how much do birth and death rates vary from year to year (environmental stochasticity), what is the impact and timing of catastrophes (if applicable), etc. etc. Where appropriate, you can paste figures, tables, maps, etc. drawn from your information sources- just make sure you say where you got these images/tables etc.
    b. What scenarios do you plan to test (e.g., management scenarios, climate change, harvest, etc), and how will these scenarios help you to address your research questions? NOTE: you don't need to have run your scenario tests- just state what scenario tests you propose to run! *It must be clear that the working model you submitted is capable of running all of your proposed scenario tests*. 
    c. Literature cited (format not important, as long as it includes all key information)  

3. Any questions for your instructor/TA about your model that you'd like to go over during our next project meeting (remember to sign up for a meeting on our shared Google Sheet!).
    
## Third project-related assignment: the written project (rough draft)!

Your final written paper is expected to be in the style of a **scientific manuscript**. That is, it should have a *title*, *introduction*, *methods*, *results*, *discussion*, *acknowledgements* and *literature cited* sections. Please also include your working PVA model (e.g., InsightMaker link or R code). 

**There are no formatting guidelines or page limits**. Please be as concise as possible while still covering all the key elements in the grading rubric. You can use any standard format for your references (e.g., APA), all we ask is that you be consistent!

### Title
A good title should be informative, should have the species name and should at least hint at what the research question is and its relevance to conservation/management.

### Introduction
This is where you introduce the topic and describe why it's important. You should also include your research questions here, along with any hypotheses that you are testing (this is usually the last paragraph of your introduction). You can recycle and flesh out the material from your proposal! This should be at least 3 paragraphs long.

Remember to cite literature here (and use a consistent format)!

The first paragraph(s) of the introduction should provide a clear motivation for your research questions. Once we read your research questions it should make total sense why you are asking these questions!

The last sentences of your introduction should state your testable research question(s).

Please try to cite at least 3-5 references in your introduction. For intro and all sections: every time you cite a paper/website/report, use the in-text citation format where you include the last name of the first author and the year of the publication. 


### Methods
This is where you describe your PVA in enough detail that it *could be replicated* by another wildlife researcher! You can recycle much of your "initial PVA" assignment here. 

Remember to justify all your decisions. Every parameter value you use (survival rates, abundance, birth rate, carrying capacity, etc.) and every factual statement you make needs to have a citation. It needs to be clear where every single number in your model came from. You also need to justify the time frame for your model- you should not just use a 20-year simulation time frame just because it is the default for InsightMaker (and if you do use a 20-year time frame you need to be very specific about why- otherwise I’ll assume you simply did not change the default!).

Unlike the "Initial PVA and Methods" assignment, this time you need to use complete sentences- no bulleted lists please! Also, try to avoid using InsightMaker jargon (RandPoisson, stocks, flows, links, ghost primitive, etc.). Instead, try to describe your model using "plain English".    

The methods section should detail more than just how you put your model together- it should also detail how you used the model to test your research questions.   

- What different scenarios did you run?    

- How did you use the simulation results to address your questions?  
    - How did you visualize the results?     
    - Did you perform any statistical analyses?  
    
In general, try to avoid including figures and tables reproduced from other studies. Just describe the key results in words and refer to the original source. Including these figures in your paper implies you created the figure yourself!

You need to define what you mean by ‘viability’, since there is no standard definition. If you are assessing minimum viable population size (MVP), you need to define your viability criterion- for example, ‘we considered populations with extinction risk less than 5% over 50 years to be viable'.

Try to avoid using acronyms like PVA and MVP without first defining what stand for.

Most of you will use female-only models- and if so you should state this explicitly, and describe how you accounted for this in your fecundity estimates (e.g., you assumed a 50% sex ratio, and therefore you multiplied the total birth rate by 50% to estimate the total number of female offspring produced per female).

For both the methods and results, use the past tense- you are describing what you did, not what you will do.

Please include a link to your InsightMaker model in your Methods section (ideally, at the top of your methods section, just to make it easier on me to find it!). If you used R, please provide your R code as an appendix.

### Results

This is where you describe and present the relevant outputs from your model. Provide figures and tables to summarize your *relevant* results. You should include at least 2-3 figures as part of your results section. Each figure should have an informative caption placed directly below the figure. 

With PVA it can be difficult to decide what to present and what not to present. Always ask yourself: is it *relevant* to your main questions?

All figures need figure numbers and captions. Figure captions can be several sentences long and should have enough detail so that a reader can understand the figure without referring to the main text. All figure captions should include the name of the species being studied, should describe what the axes represent and describe any symbols/colors that are used. Figure captions should also describe where the data come from (in most cases, a population simulation model!).

If you want to include a table from insightmaker, please import your insightmaker table results to excel so you can format nicely (rather than presenting a screenshot of an insightmaker table). Also try to avoid fractional individuals in your tables

Don’t be constrained to insightmaker’s figures! See the ["PVA" lecture](LECTURE12.html) for some examples of the kinds of figures you might make to present your results most effectively. Don't feel like you have to use R to make your figures- Excel is fine!! 

It's okay to include one or two insightmaker figures (abundance over time), but for most of you it will be better (more concise, more informative) to summarize your results in a different way (like illustrating final abundance for each scenario as a bar plot, with each scenario presented side by side). Sometimes it helps to sketch out what you want the figure to look like, and then work "backwards" to try and figure out how to make that figure.

### Discussion
This is where you describe what your results really tell us with respect to your main questions. The first paragraph in your discussion section should summarize the key results and why they are important. Include citations/references to other studies to indicate where your study fits into a broader context. I expect to see at least 3-4 in-text citations in your Discussion section.

Also, in your discussion you should:

- Describe any new questions that came up in the process of building and running your PVA
- Describe any potential flaws with your PVA and how you might improve this in the future
- Describe any future research that could be helpful in addressing your main questions 

Limit your discussion of 'flaws' in your study to a single paragraph. And don’t start your discussion section with the ‘flaws’ paragraph. Start it instead with a summary of the important results and why/how those results are important for conservation and management.
 
Let me know if you have any questions or would like to go over anything before your final submission.

A rubric for the final written presentation can be found [here](WrittenProject_rubric.docx). 

## Fourth project-related assignment: **peer review**/feedback session

In lab on Fri Apr 28 we will have a "peer review" session where we will have a chance to give each other feedback on draft manuscripts. 

The way it will work is as follows:

1. In the week before the peer review (probably Wednesday) you will receive another group's draft manuscript via WebCampus. 

2. Before lab, please thoroughly read the manuscript you have been assigned, and make comments, paying particular attention to the [grading rubric](WrittenProject_rubric.docx). 

3. During the lab period, you will first get together with the other students that were also assigned to review the same manuscript. You will have 30-35 minutes to compare notes and prepare a written peer-review of the manuscript that highlights both the strengths and the weaknesses that you found. Please make your comments as specific and constructive as possible. The goal is to give your classmates feedback that will be useful to them as they prepare their final drafts! *Please hand in your peer-review to the group that wrote the draft AND your instructor/TA* (submit/share via WebCampus)

4. After that, we will break up into new groups. One representative from each peer-review group will meet with the project group that wrote the draft manuscript, to give feedback in person.

5. For any remaining time in lab, you will have a chance to work on your write-ups and presentations!

Bring your laptops to lab as usual so you can write, save and share your peer-review electronically with your classmates/instructors.

The peer-review session will take approximately 2 hours in total, please plan accordingly!


## Fifth project-related assignment: the oral presentation!

Your group presentation should be in the style of an oral presentation at a conference. See below for guidance on giving a good oral presentation! 

Presentations will take place during our final two lab periods. 

You will have 15 minutes to give your presentations, with 2 additional minutes for questions.  

A rubric for the presentations can be found [here](presentationProject_rubric.docx)

Please plan to be in lab for the full lab period on May 5 for the final presentations. Attendance and participation as an active audience member (e.g., asking questions!) is an important part of this class.  


### Tips for a great presentation!

Here are some general notes about how to prepare and deliver a great presentation:   
- For all slides: *Less words, more pictures*! Wordy slides often cause people to stop paying attention! All of you are working with charismatic species, so you shouldn't have trouble finding nice pictures that capture people's attention. As for words, 3-5 bullet points maximum! Complete sentences are NOT needed in a presentation. Use a large, sans-serif font to improve readability.  

Note: make sure you give proper credit for all pictures (e.g., what website did it come from?)

- Excitement is infectious- make sure you convey your excitement about the project. You all worked very hard, and you should be proud of what you were able to do. Now you can share this excitement with your colleagues! Many inexperienced presenters make the mistake of highlighting only what they were *not* able to accomplish. Try to avoid this pitfall- shortcomings should be limited to a single slide in the discussion section of the presentation. 

- A good presentation should *tell a story*. It has a beginning, middle and an end. Every slide flows logically from what came before. 

- Keep it simple- don't use excess jargon, acronyms etc. Good communication skills means getting your points across in the simplest and clearest way possible. 

- Every presentation is a performance. Performance requires practice!! The real work comes before the performance- putting together the slides and practicing the delivery. When the time comes to actually give the performance, relax and have fun- the hard work is over!  

Note: please don't use fancy backgrounds- keep your slides as clean as possible. Animations can be useful, but excessive animation is distracting!

#### Title slide

- Make a catchy title! 
- Include the names and affiliations of all co-authors

#### Introduction

- Tell your audience why they should care!! All of you are working with interesting species, and all of you are asking interesting questions. All of your audience is interested in wildlife conservation and management. There is absolutely no reason why you shouldn't be able to convince your audience to care about what you have to say!!

- Cite previous research as you set up your research question. Convince us that your research fills a key knowledge gap. What is the overall context of your research? 

- After you have framed the problem, *clearly state your research questions*!

#### Methods

- Provide a *very abbreviated* summary of your PVA model. You don't have time to provide all the details that are in your written Methods section! So try to distill the key elements of your methods. Be careful you don't spend too much time on this section! The details you provide here must be clearly relevant to your research questions. All you need to do is convince your peers that your methods were appropriate for addressing your questions. 

- You can include supplemental slides that provide more details on your methods (after the last "real" slide). It can be helpful to refer to supplemental slides if someone asks a question about your methods! 


#### Results and Discussion

- Include key figures that relate to the main questions. Only include those figures that are the most relevant to your main research questions- too many figures can be distracting.  

- For all plots, make sure you explain what the axes and symbols represent! Also, make sure the axis labels are large enough to be readable from the back of the room!

- Summarize key findings- what did you learn? Make sure these findings relate to the research questions stated in the introductory slides

- Management implications- how could wildlife managers act upon your findings??

- *Just one slide* discussing shortcomings of your project and how you would improve your model and design if you had additional time. 

- Describe what you or other researchers could do to expand upon your findings- what are the next steps? 


#### Acknoweldgements   

- Your final slide should acknowledge people who helped you with your project but who are not listed as a co-author.


## Potentially useful links!

Publicly available datasets, potentially for final project...  
(many links courtesy Tom Langen) 

[Google Scholar](https://scholar.google.com/) and Web of Science (access through UNR library services) will likely be your primary tools for finding papers!

### BIODIVERSITY DATA CLEARINGHOUSES /ARCHIVES
[International Union for the Conservation of Nature (IUCN) Redlist](http://www.iucnredlist.org/) (Searchable list of the world’s threatened and endangered plants and animal species on the IUCN Redlist.)  

[Conservation International Global Biodiversity Hotspots](http://www.biodiversityhotspots.org/Pages/default.aspx) (Detailed data on the attributes and threats to the world’s global biodiversity hotspots.)  

[National Biological Information Infrastructure](http://www.nbii.gov/) (Data archive and clearinghouse for biological data from the US. Also provides standards for metadata.)  

[Biological Inventories of the World’s Protected Areas](http://www.ice.ucdavis.edu/bioinventory/bioinventory.html) (Searchable species occurrence records and species lists for over 1,400 protected areas around the globe.)  

[Global Biodiversity Information Facility](http://data.gbif.org/welcome.htm) (An enormous clearinghouse of biodiversity data) 

[USGS avian data portal](https://migbirdapps.fws.gov/mbdc/databases/db_selection.html)     

[Global Population Dynamics Data Base(GPDD)](http://www3.imperial.ac.uk/cpb/research/patternsandprocesses/gpdd) (5000 population size time series for 1400 species, most of which have at least ten years of data. There are data on the natural history of the organism and the location & method of sampling.)   

[GPDD, alternative link](https://www.imperial.ac.uk/cpb/gpdd2/secure/login.aspx)     

[USGS Breeding Bird Survey](http://www.pwrc.usgs.gov/BBS/) (Breeding bird survey data back to 1966)  

[Bird Point Count Database](http://www.pwrc.usgs.gov/point/) (Depository of bird point-count data from across the US.)   

[Bird Studies Canada Nature Counts](http://www.bsc-eoc.org/birdmon/default/main.jsp) (Bird survey data archive for Canada, includes point counts and many other types of surveys.)  

[Avian Knowledge Network](http://www.avianknowledge.net/content/datasets)  (Archive of aggregated bird surveys from many organizations and studies across throughout the western hemisphere, including Latin America.)  

[NatureServe](http://www.natureserve.org/getData/index.jsp)  (Data on species of plants and animals in the Western Hemisphere, including detailed range maps) 

[USGS bat data portal](https://my.usgs.gov/bpd/)     
 
[Comadre and Compadre matrix demography database](https://compadredb.wordpress.com/2015/10/05/introducing-the-comadre-animal-matrix-database/)    

### GOVERNMENT AGENCY DATA PORTALS 

[National Atlas](http://www.nationalatlas.gov/) (Geospatial data on the environment, economy, and people of the US).   

[US Department of Agriculture Census of Agricultural Data](http://www.agcensus.usda.gov/) (Authoritative data on all aspects of agriculture in the US.)      

[Centers for Disease Control & Prevention Data & Statistics](http://www.cdc.gov/datastatistics/) (Comprehensive data on all aspects of disease epidemiology.)     

[USGS Water Data for the Nation](http://waterdata.usgs.gov/nwis) (Hydrological and water-quality data from across the US.)  

[USGS Survey Disease Maps](http://diseasemaps.usgs.gov/index.html) (US County-scale maps of incidence patterns of various mosquito-vectored diseases)    

[The Multi-resolution Land Characteristics Consortium (MRLC) National Land Cover Database](http://www.mrlc.gov/) (Land cover or land use, canopy cover, and impermeable surface area of the entire US, at a resolution of 30 m x 30 m, based on remote sensing data from satellite imagery.)  

[US Fish & Wildlife Service National Wetlands Inventory](http://www.fws.gov/wetlands/) (Wetlands greater than 1 acre are mapped and classified throughout the US, Puerto Rico and US territories. Data can be examined using the [Wetland Mapper](http://www.fws.gov/wetlands/Data/Mapper.html) and then downloaded for use by a GIS application, or can by inspected directly using [Google Earth](http://www.fws.gov/wetlands/Data/GoogleEarth.html))   

[USDA Forest Inventory and Analysis National Program](http://fia.fs.fed.us/) 
[Forest Inventory Data Online (FIDO)](http://fia.fs.fed.us/tools-data/default.asp) (Highly-detailed periodic surveys of forest composition at sites throughout the US.)   

[US Geological Survey](http://www.usgs.gov/) (Reports, data analysis, maps, and raw data on a diversity of topics related to environmental science, including biodiversity and emerging diseases.)

[NOAA National Climate Data Center](http://www.ncdc.noaa.gov/oa/ncdc.html) (Extensive data archives of climate data, including paleoclimate.)

### ENVIRONMENTAL DATA CLEARINGHOUSES
[Ecotrends](http://www.ecotrends.info/EcoTrends/) (Data archive and data visualization tools for ecological data at sites distributed around the US.)  

[NASA Global Change Master Directory](http://gcmd.nasa.gov/index.html) (Data on all aspects of global change, includes data on climate, land use, biodiversity and human dimensions.)  

[Oak Ridge National Laboratory Distributed Active Archive Center for Biogeochemical Dynamics(ORNL DAAC)](http://daac.ornl.gov/index.shtml) (A NASA-sponsored source for biogeochemical and ecological data and models useful in environmental research.)  

[Pole to Pole Ecological Research Lattice of Sites (P2ERLS)](http://www.p2erls.net/) (Portal to research stations and research networks, including their data archives.)  

[Weatherspark](http://weatherspark.com/) (Visualized time-series data on local climate at sites around the globe.)  

[Long Term Ecological Research (LTER) Network](http://www.lternet.edu/) (Network of research stations that have standardized monitoring programs as well as site-specific research. Sites are mandated to make data publicly available on the web.)  


### RESEARCH PROJECT DATA ARCHIVES
[Dryad](http://datadryad.org/) (Data archives for bioscience data from peer-reviewed journal articles from a large consortium of journals)   

[Ecological Society of America (ESA) Data Registry](http://esapubs.org/archive/archive_D.htm)
Archive of ecological and environmental data from ESA publications)  

[National Center for Ecological Assessment & Synthesis (NCEAS) Data Repository](http://knb.ecoinformatics.org/knb/style/skins/nceas/index.jsp) (Data archive of contributed data sets of all types of ecological data.)  

[NCEAS Scientific Computing Database](http://www.nceas.ucsb.edu/scicomp/) (Clearinghouse of climatological, geospatial, and other data. Also has shareware software for analysis.)
































