---
title: "Final class review"
author: "NRES 470/670"
date: "Spring 2023"
output: 
  html_document: 
    theme: spacelab
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
```


### Upcoming final exam

**when and where** The (optional) final exam is on Friday **May 12** (9:50am to 11:50) in our regular classroom. You will have the whole two hour period to take the exam (but you should not need the whole period). The exam will be in the same basic format as the midterm exams.

**what** The exam will cover all material covered in lectures and lab.

- All material in Chapters 1-6 of the Gotelli book:
    * Chapter 1: Exponential growth
    * Chapter 2: Logistic growth
    * Chapter 3: Age structured population and matrix models
    * Chapter 4: Metapopulations
    * Chapter 5: Competition
    * Chapter 6: Predation
- All material covered in lectures, including the following web pages and corresponding lectures and top hat pages:    
    * [Systems thinking and modeling](LECTURE1.html)
    * [Exponential growth](LECTURE2.html)
    * [Malthus and limits to growth](LECTURE3.html)
    * [Logistic population growth](LECTURE4.html)
    * [Allee effect](LECTURE5.html)
    * [Age-structured populations](LECTURE6.html)
    * [Matrix population models](LECTURE7.html)
    * ["Embracing" uncertainty](LECTURE8.html) 
    * [Small-population paradigm](LECTURE9.html)
    * [Declining-population paradigm](LECTURE11.html) 
    * [Population Viability Analysis](LECTURE12.html)
    * [Metapopulations and source-sink dynamics](LECTURE13.html)]
    * [Parameter estimation](LECTURE15.html) [NOTE: this topic will not be covered in the exam this year]
    * [Competition models](LECTURE16.html)
    * [Predation models](LECTURE17.html)
    * NOTE: all lectures have been recorded and are available via the "Zoom" link on WebCampus in case you missed any or in case you'd like to use these recordings as review/study materials   
- All material covered in labs 1-6, including:
    * [Lab 1: exponential growth](LAB1.html)
    * [Lab 2: logistic growth](LAB2.html)
    * [Lab 3: age-structured populations](LAB3.html)
    * [Lab 4: matrix population models](LAB4.html)
    * [Lab 5: stochasticity and uncertainty](LAB5.html)
    * [Lab 6: metapopulations](LAB6.html)
- Basic programming concepts:
    * Conditional logic (IF-THEN-ELSE): see examples in Malthus and Allee effect lectures
    * Iteration ('FOR loops'): see examples in Lab 1 and Lab 4. 
    * NOTE: you will NOT be tested on how to run population models in R (or how to do anything else in R).    

*The exam will consist of a mixture of multiple-choice and short-answer questions.*  

We will do an optional review session in class on Wed May 10 (regular class time, regular classroom). Please make note of any questions that come up as you study- we can talk these over during the review session! 

Sage will also provide an additional final office hour on Thursday May 11 (look for announcement).

NOTE: we skipped over the [lecture on individual-based models](LECTURE10.html) and the [lecture on parameter estimation](LECTURE15.html)- these topics will *not be included on the final exam*

*The exam will consist of a mixture of multiple-choice and short-answer questions (perhaps including a few definitions).*

### Final logistics

#### Final exam

- Friday, May 12 from 9:50-11:50 in our regular classroom.

#### Final papers

- Everyone has received detailed feedback from peer review and instructors. Please let me and/or your TA know if you have any questions. We can not do additional full reviews of your paper but you're welcome to send short sections for us to look at and we will try to provide comments as quickly as we can! 
- Final papers due May 15 at 5pm (WebCampus submission)

#### Extra credit

- Will accept up to two extra credit write-ups
- Submit extra credit assignments via webcampus (file submission) -- one submission per each assignment.
- Due when final papers are due, by Mon May 15 at 11:59pm).

#### Review session

- Wed 5/10 at 10am in our regular classroom.

#### PLEASE fill out your course evaluations!





[--this is the final lecture--]


























